{
 "title": "App Metrics - Reservoirs Sample",
 "description": "Dashboard to demonstrate reservoirs supported by App Metrics",
 "tags": [ "InfluxDB" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Exponential Decay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Default Forward Decaying Reservoir",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "reservoirs__exponentially-decaying",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Median" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Uniform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Algorithm R Reservoir",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "reservoirs__uniform",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Median" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Sliding Window", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sliding Window Reservoir",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "reservoirs__sliding-window",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Median" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}